 drop table usuappadmin
CREATE TABLE USUAPPADMIN(
ID_USU INT IDENTITY(1,1),
NOMBRE	VARCHAR(100),
CODIGO	VARCHAR(100),
PASSWOORD VARCHAR(MAX)
);

INSERT INTO USUAPPADMIN
VALUES
('ADMINISTRADOR', 'USUWEBADMIN', 'db14cee3de5fa75b2061997e2e0df479');

--DELETE FROM USUAPPADMIN

 SELECT * FROM USUAPPADMIN
  WHERE CODIGO='USUWEBADMIN' AND PASSWOORD ='09*ADMIN$uno'
