CREATE TABLE USUAPPADMIN(
ID_USU INT IDENTITY(1,1),
NOMBRE	VARCHAR(100),
CODIGO	VARCHAR(100),
PASSWOORD VARCHAR(25)
);

INSERT INTO USUAPPADMIN
VALUES
('ADMINISTRADOR', 'USUWEBADMIN', '09*ADMIN$uno');

--DELETE FROM USUAPPADMIN

 SELECT CODIGO, NOMBRE FROM USUAPPADMIN WHERE CODIGO='USUWEBADMIN' AND PASSWOORD ='09*ADMIN$uno'
